name: "Build Choco with Dongle"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["choco_left", "choco_right", "choco_dongle", "settings_reset"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      custom_config: '["#define MIRYOKU_CLIPBOARD_MAC"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y\\nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y"]'
