name: "Build Choco Prospector Dongle"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["xiao_ble"]'
      shield: '["choco_dongle prospector_adapter", "settings_reset"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      custom_config: '["#define MIRYOKU_CLIPBOARD_MAC"]'
      modules: '["carrefinho/prospector-zmk-module/core/zephyr-4-1"]'